//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Derivco.MSBuild.Tasks.CommonAssemblyInfo    
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyCompany("Microgaming")]
[assembly: AssemblyCopyright("Copyright © Microgaming 1996-2019 All rights reserved")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0.0")]
[assembly: AssemblyProduct("MoneyWheel")]
[assembly: AssemblyVersion("1.0.0.0")]
